version: '3.1'

services:
  Node:
    image: sample-node 
    environment:
    - DB_NAME=database_node
    - DB_HOST=localhost 
    - DB_PASS=password
    ports:
      - 3000:3000
    working_dir: /app
    networks:
    - nodenetworks

  database_node:
    image: postgres:11.2-alpine
    container_name: postgress
    environment:
    - DB_NAME=database_node
    - DB_HOST=localhost 
    - DB_PASS=password
    volumes:
      - postgressbkp:/data/db
    restart: always
    networks:
    - nodenetworks
    
volumes:
  postgressbkp:
networks:
  nodenetworks:
